name: Zip Release
  # You may pin to the exact commit or the version.
  # uses: TheDoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
  uses: TheDoctor0/zip-release@0.6.2
  with:
    # Filename for archive
    filename: dss.zip
    # Base path for archive files
    path: # optional, default is .
    # Working directory before zipping
    directory: # optional, default is .
    # List of excluded files / directories
    exclusions: dss.zip
    # List of excluded files / directories with recursive wildcards (only applies on Windows with `zip` type)
    recursive_exclusions: # optional, default is 
    # Tool to use for archiving
    type: # optional, default is zip

